import { Platform, StyleSheet } from 'react-native';

import { borderWidths, radii } from '../theme/tokens';

export const WEB_MAX_WIDTH = 520;

export const styles = StyleSheet.create({
  safeArea: { flex: 1 },
  safeAreaWeb: {
    overflow: 'hidden',
  },
  webStage: {
    flex: 1,
    width: '100%',
    alignItems: 'center',
  },
  bgBlobTop: {
    position: 'absolute',
    top: -70,
    right: -40,
    width: 220,
    height: 220,
    borderRadius: 120,
    opacity: 0.65,
  },
  bgBlobBottom: {
    position: 'absolute',
    bottom: -70,
    left: -40,
    width: 220,
    height: 220,
    borderRadius: 120,
    opacity: 0.55,
  },
  mainWrap: { flex: 1, width: '100%', maxWidth: WEB_MAX_WIDTH },
  keyboardAvoidingView: { flex: 1 },
  container: { padding: 16, paddingTop: 50, paddingBottom: 110, gap: 12 },
  heroCard: {
    borderRadius: radii.xl,
    borderWidth: borderWidths.thick,
    padding: 14,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    boxShadow: '0px 2px 4px rgba(115, 75, 40, 0.08)',
    elevation: 1,
  },
  logo: {
    width: 62,
    height: 62,
    borderRadius: radii.md,
    borderWidth: borderWidths.thick,
    backgroundColor: '#fff',
  },
  heroTextWrap: { flex: 1 },
  title: { fontSize: 30, fontWeight: '800', letterSpacing: 0.3 },
  subtitle: { fontSize: 13, marginTop: 2 },
  card: {
    borderRadius: radii.lg,
    padding: 12,
    borderWidth: borderWidths.thick,
    gap: 8,
    boxShadow: '0px 1px 2px rgba(89, 66, 45, 0.05)',
    elevation: 1,
  },
  cardHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 8,
  },
  headerActionsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  cardTitle: { fontSize: 18, fontWeight: '700' },
  statusWrap: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  statusDot: { width: 10, height: 10, borderRadius: 5, borderWidth: 1 },
  statusText: { fontSize: 12, fontWeight: '600' },
  input: { borderWidth: borderWidths.thick, borderRadius: radii.md, paddingHorizontal: 10, paddingVertical: 9, fontSize: 14 },
  row: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  button: { borderRadius: radii.md, paddingHorizontal: 12, paddingVertical: 10, borderWidth: borderWidths.thick },
  buttonDisabled: { opacity: 0.55 },
  buttonText: { fontWeight: '700' },
  hint: { fontSize: 13 },
  connectionItem: {
    borderWidth: borderWidths.thick,
    borderRadius: radii.md,
    padding: 10,
    gap: 2,
    marginBottom: 8,
    flexDirection: 'row',
    alignItems: 'center',
  },
  connectionMainArea: {
    flex: 1,
    gap: 2,
  },
  connectionEditButton: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#9b7c5f',
    backgroundColor: 'rgba(255,255,255,0.7)',
  },
  connectionEditText: {
    fontSize: 12,
    fontWeight: '700',
  },
  connectionName: { fontWeight: '700' },
  connectionMeta: { fontSize: 12 },
  heroStatusWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 999,
    backgroundColor: 'rgba(255,255,255,0.6)',
  },
  heroStatusText: {
    fontSize: 12,
    fontWeight: '700',
  },
  foldToggleText: {
    fontSize: 12,
    fontWeight: '700',
    textDecorationLine: 'underline',
  },
  floatingBarWrap: { position: 'absolute', left: 0, right: 0, bottom: 14, alignItems: 'center', justifyContent: 'center',zIndex: 10 },
  floatingBar: {
    width: '95%',
    maxWidth: WEB_MAX_WIDTH - 48,
    borderRadius: radii.round,
    borderWidth: borderWidths.thick,
    height: 60,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 26,
    boxShadow: '0px 4px 8px rgba(0,0,0,0.12)',
    elevation: 5,
  },
  tabButton: { minWidth: 70, alignItems: 'center' },
  tabButtonText: { fontSize: 12, fontWeight: '700', marginTop: 2 },
  chatButtonPlaceholder: { width: 88 },
  chatFab: {
    position: 'absolute',
    top: -16,
    minWidth: 88,
    height: 52,
    borderRadius: 26,
    borderWidth: borderWidths.thick,
    paddingHorizontal: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    boxShadow: '0px 4px 8px rgba(0,0,0,0.16)',
    elevation: 6,
  },
  chatFabDisabled: {
    opacity: 1,
    boxShadow: '0px 2px 4px rgba(0,0,0,0.08)',
    elevation: 2,
  },
  chatFabText: { fontWeight: '800', fontSize: 14 },
  modalBackdrop: { flex: 1, backgroundColor: 'rgba(0,0,0,0.22)', alignItems: 'center' },
  modalOverlay: {
    ...StyleSheet.absoluteFill,
    zIndex: 1,
  },
  chatSheetAvoid: {
    position: 'absolute',
    left: 0,
    right: 0,
    maxHeight:'95%',
    minHeight:'60%',
    bottom: 0,
    width: '100%',
    maxWidth: WEB_MAX_WIDTH,
    alignSelf: 'center',
    zIndex: 2,
    elevation: 8,
  },
  chatSheetAvoidWeb: {
    left: undefined,
    right: undefined,
    width: '100%',
    height: '100%',
    margin:'auto',
    alignSelf: 'center',
  },
  chatSheet: {
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    borderBottomLeftRadius: 0,
    borderBottomRightRadius: 0,
    borderWidth: borderWidths.thick,
    borderBottomWidth: 0,
    padding: 12,
    paddingBottom: Platform.OS === 'ios' ? 34 : 14,
    gap: 8,
    height: '100%',
    width: '100%',
    marginBottom: 0,
  },
  chatSheetHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  chatHeaderRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  thinkingChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 999,
    backgroundColor: 'rgba(255,255,255,0.7)',
  },
  thinkingChipText: {
    fontSize: 12,
    fontWeight: '700',
  },
  phaseText: {
    fontSize: 12,
    fontWeight: '600',
    marginTop: -2,
  },
  stepsPanel: {
    borderWidth: 1,
    borderRadius: 10,
    padding: 8,
    backgroundColor: 'rgba(255,255,255,0.6)',
  },
  stepsHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  stepsTitle: {
    fontSize: 12,
    fontWeight: '700',
  },
  stepsToggle: {
    fontSize: 12,
    fontWeight: '700',
  },
  stepsList: {
    marginTop: 8,
    gap: 5,
  },
  stepRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  stepIndex: {
    width: 16,
    fontSize: 12,
    fontWeight: '600',
  },
  stepName: {
    flex: 1,
    fontSize: 12,
    fontWeight: '600',
  },
  stepStatus: {
    fontSize: 12,
    fontWeight: '700',
  },
  chatToolsRow: { flexDirection: 'row', gap: 10 },
  toolButton: { paddingVertical: 2 },
  toolButtonText: { fontSize: 12, fontWeight: '700' },
  toolButtonTextDisabled: { color: '#b59e87' },
  chatBox: { borderWidth: borderWidths.thick, borderRadius: radii.md, minHeight: 220, backgroundColor: '#fffefc' },
  chatBoxContent: { padding: 10, gap: 8 },
  chatComposerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  chatInputInlineGrow: {
    flex: 1,
  },
  bubbleRow: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'flex-end',
    gap: 6,
  },
  userBubbleRow: {
    justifyContent: 'flex-end',
  },
  assistantBubbleRow: {
    justifyContent: 'flex-start',
  },
  assistantAvatar: {
    width: 22,
    height: 22,
    borderRadius: 11,
    borderWidth: 1,
    borderColor: '#00000022',
    backgroundColor: '#fff',
    marginBottom: 2,
  },
  bubble: { borderRadius: radii.md, borderWidth: borderWidths.thick, padding: 10 },
  userBubbleWrap: {
    maxWidth: '72%',
    minWidth: '28%',
  },
  assistantBubbleWrap: {
    maxWidth: '84%',
    minWidth: '30%',
  },
  bubbleHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 4 },
  bubbleRole: { fontSize: 12, fontWeight: '700' },
  bubbleTime: { fontSize: 11, fontWeight: '600' },
  bubbleText: { fontSize: 14, lineHeight: 20 },
  thinkingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingVertical: 2,
  },
  thinkingText: {
    fontSize: 13,
    fontWeight: '600',
  },
  skeletonWrap: {
    gap: 8,
    paddingVertical: 2,
  },
  skeletonLineLg: {
    height: 8,
    borderRadius: 999,
    backgroundColor: '#00000022',
    width: '92%',
  },
  skeletonLineMd: {
    height: 8,
    borderRadius: 999,
    backgroundColor: '#00000018',
    width: '78%',
  },
  skeletonLineSm: {
    height: 8,
    borderRadius: 999,
    backgroundColor: '#00000014',
    width: '56%',
  },
  settingLabel: { fontSize: 14, fontWeight: '700', marginTop: 4 },
  versionRow: {
    gap: 2,
  },
  helpBox: {
    borderWidth: 1,
    borderColor: '#d6d3d1',
    borderRadius: 10,
    backgroundColor: 'rgba(255,255,255,0.7)',
    padding: 8,
    gap: 4,
  },
  helpText: {
    fontSize: 12,
    lineHeight: 17,
  },
  contactLinkButton: {
    borderWidth: 1,
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  contactLinkText: {
    fontSize: 13,
    fontWeight: '700',
  },
});
